#!/bin/tcsh

#SBATCH --job-name="composite_input-times-grad_maps"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=160G
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=06:00:00
#SBATCH --array=1-3
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=composite_input-times-grad_maps_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_standalone/ml4convection"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_models/experiment13a"
set TOP_PREDICTOR_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_project/predictors/quality_controlled/partial_grids"
set TOP_TARGET_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_project/targets/new_echo_classification/no_tracking/omit_north_radar/partial_grids"

set L2_WEIGHTS=(0.0000010000 0.0000010000 0.0000010000)
set LAG_TIME_STRINGS_DASHED=("0-600-1200" "0-600-1200" "0-600-1200")
set DESCRIPTION_STRINGS=("highest-probs" "lowest-probs" "medium-probs")

set l2_weight=${L2_WEIGHTS[$SLURM_ARRAY_TASK_ID]}
set lag_time_string_dashed=${LAG_TIME_STRINGS_DASHED[$SLURM_ARRAY_TASK_ID]}
set description_string=${DESCRIPTION_STRINGS[$SLURM_ARRAY_TASK_ID]}

set l2_weight_string=`printf "%.10f" $l2_weight`

set model_dir_name="${TOP_MODEL_DIR_NAME}/l2-weight=${l2_weight_string}_lag-times-sec=${lag_time_string_dashed}"
set saliency_dir_name="${model_dir_name}/validation/partial_grids/interesting_examples/input_times_grad_${description_string}"
set output_file_name="${model_dir_name}/validation/partial_grids/interesting_examples/input_times_grad_${description_string}_composite.nc"

python3 -u "${CODE_DIR_NAME}/composite_saliency_maps.py" \
--input_saliency_dir_name="${saliency_dir_name}" \
--input_predictor_dir_name="${TOP_PREDICTOR_DIR_NAME}" \
--input_target_dir_name="${TOP_TARGET_DIR_NAME}" \
--first_date_string="20170101" \
--last_date_string="20171224" \
--max_pmm_percentile_level=99 \
--output_file_name="${output_file_name}"
