#!/bin/tcsh

#SBATCH --job-name="plot_discard_test_fancy_stdev"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=01:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=plot_discard_test_fancy_stdev_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_standalone/ml4convection"
set MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_models/qfss_experiment01/fss-weight=06.0_num-quantile-levels=017"

set input_file_name="${MODEL_DIR_NAME}/testing_with_uq/partial_grids/evaluation_fancy_stdev/discard_test_matching-distance-px=0.000000.nc"
set output_file_name="${MODEL_DIR_NAME}/testing_with_uq/partial_grids/evaluation_fancy_stdev/discard_test_matching-distance-px=0.000000.jpg"

python3 -u "${CODE_DIR_NAME}/plot_discard_test.py" \
--input_file_name="${input_file_name}" \
--output_file_name="${output_file_name}"
