#!/bin/tcsh

#SBATCH --job-name="run_discard_test_fancy_stdev"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=12:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=run_discard_test_fancy_stdev_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_standalone/ml4convection"
set MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_models/qfss_experiment01/fss-weight=06.0_num-quantile-levels=017"

set prediction_dir_name="${MODEL_DIR_NAME}/testing_with_uq/partial_grids"

python3 -u "${CODE_DIR_NAME}/run_discard_test.py" \
--input_prediction_dir_name="${prediction_dir_name}" \
--first_date_string="20180101" \
--last_date_string="20181231" \
--time_interval_steps=1 \
--use_fss=0 \
--is_error_pos_oriented=0 \
--matching_distances_px 0 \
--discard_fractions 0.05 0.10 0.15 0.20 0.25 0.30 0.35 0.40 0.45 0.50 0.55 0.60 0.65 0.70 0.75 0.80 0.85 0.90 0.95 \
--use_fancy_quantile_method_for_stdev=1 \
--output_dir_name="${prediction_dir_name}/evaluation_fancy_stdev"
