#!/bin/tcsh

#SBATCH --job-name="apply_neural_nets"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=30:00:00
#SBATCH --array=1-60
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_neural_nets_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_standalone/ml4convection"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_models/crps_test"
set TOP_PREDICTOR_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_project/predictors/quality_controlled/partial_grids"
set TOP_TARGET_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_project/targets/new_echo_classification/no_tracking/omit_north_radar/partial_grids"

set LOSS_FUNCTION_NAMES=("crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4" "crps_neigh2" "crps_neigh3" "crps_neigh4" "crpsfss_neigh4")
set DATE_STRINGS=("20170101" "20170101" "20170101" "20170101" "20170202" "20170202" "20170202" "20170202" "20170303" "20170303" "20170303" "20170303" "20170404" "20170404" "20170404" "20170404" "20170505" "20170505" "20170505" "20170505" "20170606" "20170606" "20170606" "20170606" "20170707" "20170707" "20170707" "20170707" "20170808" "20170808" "20170808" "20170808" "20170909" "20170909" "20170909" "20170909" "20171010" "20171010" "20171010" "20171010" "20171111" "20171111" "20171111" "20171111" "20171212" "20171212" "20171212" "20171212" "20180125" "20180125" "20180125" "20180125" "20180603" "20180603" "20180603" "20180603" "20180823" "20180823" "20180823" "20180823")

set loss_function_name=${LOSS_FUNCTION_NAMES[$SLURM_ARRAY_TASK_ID]}
set date_string=${DATE_STRINGS[$SLURM_ARRAY_TASK_ID]}

set model_dir_name="${TOP_MODEL_DIR_NAME}/${loss_function_name}"
set model_file_name="${model_dir_name}/model.h5"
set prediction_dir_name="${model_dir_name}/validation/partial_grids"

python3 -u "${CODE_DIR_NAME}/apply_neural_net.py" \
--input_model_file_name="${model_file_name}" \
--input_predictor_dir_name="${TOP_PREDICTOR_DIR_NAME}" \
--input_target_dir_name="${TOP_TARGET_DIR_NAME}" \
--apply_to_full_grids=0 \
--first_valid_date_string="${date_string}" \
--last_valid_date_string="${date_string}" \
--output_dir_name="${prediction_dir_name}"
