#!/bin/tcsh

#SBATCH --job-name="plot_backwards_perm_test"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=30:00:00
#SBATCH --array=1
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=plot_backwards_perm_test_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_standalone/ml4convection"
set TOP_MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_models/experiment13d"

set L2_WEIGHTS=(0.0000010000)
set LAG_TIME_STRINGS_DASHED=("0-1200-2400-3600")

set l2_weight=${L2_WEIGHTS[$SLURM_ARRAY_TASK_ID]}
set lag_time_string_dashed=${LAG_TIME_STRINGS_DASHED[$SLURM_ARRAY_TASK_ID]}
set l2_weight_string=`printf "%.10f" $l2_weight`

set model_dir_name="${TOP_MODEL_DIR_NAME}/l2-weight=${l2_weight_string}_lag-times-sec=${lag_time_string_dashed}"
set input_file_name="${model_dir_name}/testing/partial_grids/permutation_test_backwards.p"
set output_dir_name="${model_dir_name}/testing/partial_grids/permutation_test_backwards"

python3 -u "${CODE_DIR_NAME}/plot_permutation_results.py" \
--input_file_name="${input_file_name}" \
--confidence_level=0.99 \
--output_dir_name="${output_dir_name}"
