#!/bin/tcsh

#SBATCH --job-name="compute_advanced_monthly_scores"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=8G
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=03:00:00
#SBATCH --array=1
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=compute_advanced_monthly_scores_%A_%a.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_standalone/ml4convection"
set TOP_TARGET_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_project/targets/new_echo_classification/no_tracking/omit_north_radar/full_grids"
set MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_models/experiment13b/persistence_model"

set SMOOTHING_RADII_PX=(4)
set smoothing_radius_px=${SMOOTHING_RADII_PX[$SLURM_ARRAY_TASK_ID]}
set smoothing_radius_string=`printf "%1d" $smoothing_radius_px`

set evaluation_dir_name="${MODEL_DIR_NAME}/testing/smooth${smoothing_radius_string}/evaluation/matching_distance_px=4.000000"

set MONTHS=(1 2 3 4 5 6 7 8 9 10 11 12)
set i=1

while ($i <= ${#MONTHS})
    python3 -u "${CODE_DIR_NAME}/compute_advanced_scores_ungridded.py" \
    --input_basic_score_dir_name="${evaluation_dir_name}" \
    --first_date_string="20180101" \
    --last_date_string="20181224" \
    --use_partial_grids=0 \
    --desired_month=${MONTHS[$i]} \
    --split_by_hour=0 \
    --input_climo_file_name="${TOP_TARGET_DIR_NAME}/climo_dilation-distance-px=4.000000.p" \
    --output_dir_name="${evaluation_dir_name}"

    @ i = $i + 1
end
