#!/bin/tcsh

#SBATCH --job-name="apply_model"
#SBATCH --partition="fge"
#SBATCH --account="rda-ghpcs"
#SBATCH --qos="batch"
#SBATCH --ntasks=1
#SBATCH --nodes=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=128G
##SBATCH --nodes=1
##SBATCH --ntasks=1
##SBATCH --cpus-per-task=1
##SBATCH --ntasks-per-node=1
#SBATCH --time=06:00:00
#SBATCH --exclude=h28n12
##SBATCH --exclude=h31n03,h28n12
##SBATCH --exclude=h29n01,h26n05,h28n06,h29n07,h30n03,h30n15
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=ryan.lagerquist@noaa.gov
#SBATCH --output=apply_model_%A.out

module load cuda/10.1
source /scratch2/BMC/gsd-hpcs/Jebb.Q.Stewart/conda3.7/etc/profile.d/conda.csh
conda activate base

set CODE_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_standalone/ml4convection"
set TOP_TARGET_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_project/targets/new_echo_classification/no_tracking/omit_north_radar/full_grids"
set MODEL_DIR_NAME="/scratch1/RDARCH/rda-ghpcs/Ryan.Lagerquist/ml4convection_models/experiment13e/persistence_model"

set FIRST_VALIDN_DATE_STRING="20180101"
set LAST_VALIDN_DATE_STRING="20181224"

python3 -u "${CODE_DIR_NAME}/apply_persistence_model.py" \
--input_target_dir_name="${TOP_TARGET_DIR_NAME}" \
--lead_time_seconds=7200 \
--smoothing_radius_px=0 \
--first_valid_date_string="${FIRST_VALIDN_DATE_STRING}" \
--last_valid_date_string="${LAST_VALIDN_DATE_STRING}" \
--output_dummy_model_file_name="${MODEL_DIR_NAME}/model.h5" \
--output_dir_name="${MODEL_DIR_NAME}/testing"
